services:
  nominatim:
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
    container_name: nominatim
    build:
      context: .
      args:
        NOMINATIM_VERSION: 5.1.0
        USER_AGENT: mediagis/nominatim-docker:5.1.0
    ports:
      - "8081:8080"

    environment:
      # External RDS Configuration
      PGHOST: nominatimdb.c7gqmm4ayxos.eu-west-3.rds.amazonaws.com
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: Oussama0909!
      NOMINATIM_PASSWORD: Oussama0909!
      PGDATABASE: nominatimdb      
      THREADS: 4
      NOMINATIM_DATABASE_DSN: pgsql:host=nominatimdb.c7gqmm4ayxos.eu-west-3.rds.amazonaws.com;port=5432;user=postgres;password=Oussama0909!;dbname=nominatim

    shm_size: 1gb

