version: '3.8'

services:
  nominatim:
    container_name: nominatim-production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NOMINATIM_VERSION: 5.1.0
        USER_AGENT: nominatim-production:5.1.0
    
    ports:
      - "8080:8080"
    
    volumes:
      # EFS mount for OSM data storage
      - efs-data:/efs
      # Optional: Local data directory for development
      - ./data:/nominatim/data
    
    environment:
      # Database Configuration (use secrets in production)
      PGHOST: ${PGHOST:-localhost}
      PGPORT: ${PGPORT:-5432}
      PGDATABASE: ${PGDATABASE:-nominatim}
      PGUSER: ${PGUSER:-nominatim}
      PGPASSWORD: ${PGPASSWORD}
      NOMINATIM_PASSWORD: ${NOMINATIM_PASSWORD}
      
      # OSM Data Configuration
      PBF_URL: ${PBF_URL}
      PBF_PATH: ${PBF_PATH}
      REPLICATION_URL: ${REPLICATION_URL}
      IMPORT_STYLE: ${IMPORT_STYLE:-full}
      REVERSE_ONLY: ${REVERSE_ONLY:-false}
      KEEP_PBF: ${KEEP_PBF:-true}
      
      # Performance Configuration
      THREADS: ${THREADS:-4}
      OSM2PGSQL_CACHE: ${OSM2PGSQL_CACHE:-4000}
      NOMINATIM_API_POOL_SIZE: ${NOMINATIM_API_POOL_SIZE:-10}
      NOMINATIM_QUERY_TIMEOUT: ${NOMINATIM_QUERY_TIMEOUT:-60}
      NOMINATIM_REQUEST_TIMEOUT: ${NOMINATIM_REQUEST_TIMEOUT:-60}
      
      # Import options optimized for production
      NOMINATIM_OSMI_IMPORT_OPTIONS: "--slim --drop --hstore-all --cache 4000 --number-processes 4"
    
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    restart: unless-stopped
    
    # Shared memory for PostgreSQL operations
    shm_size: 2gb
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  efs-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/efs  # This should be your EFS mount point

networks:
  default:
    name: nominatim-network

